version: 2
registries:
  github-packages:
    type: maven-repository
    url: https://maven.pkg.github.com/revanced/registry
    username: x-access-token
    password: ${{ secrets.REVANCED_REGISTRY_TOKEN }}

updates:
  - package-ecosystem: github-actions
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: monthly

  - package-ecosystem: npm
    labels: []
    directory: /
    target-branch: dev
    schedule:
      interval: monthly

  - package-ecosystem: gradle
    labels: []
    registries:
      - github-packages
    directory: /
    target-branch: dev
    schedule:
      interval: monthly
